function [etat_ia, proba_sain, proba_faible, proba_grave] = ...
    predict_BK4_bloc(T_bobA, T_bobB, T_bobC, ...
                     T_pal_DE, T_pal_NDE, T_huile, ...
                     T_pal1_red, T_pal2_red, ...
                     vib_moteur, vib_red, pos_galet)
%#codegen

% Déclare predict_BK4 comme fonction externe
coder.extrinsic('predict_BK4');

% Initialisation obligatoire
etat_ia      = double(0);
proba_sain   = double(0);
proba_faible = double(0);
proba_grave  = double(0);

% Appel
[etat_ia, proba_sain, proba_faible, proba_grave] = predict_BK4(...
    T_bobA, T_bobB, T_bobC, ...
    T_pal_DE, T_pal_NDE, T_huile, ...
    T_pal1_red, T_pal2_red, ...
    vib_moteur, vib_red, pos_galet);
