function bloc_envoyer(wm, w_table, ...
    T_bobA, T_bobB, T_bobC, ...
    T_pal_DE, T_pal_NDE, T_huile, ...
    T_pal1_red, T_pal2_red, ...
    vib_moteur, vib_red, pos_galet, ...;
    w_separateur, ...
    P_hydr1, P_hydr2, ...
    pression_pompe1, pression_pompe2, ...
    contre_pression1, contre_pression2, ...
    etat_ia, proba_sain, proba_faible, proba_grave, ...
    RUL_moteur, RUL_reducteur, tendance_mot, tendance_red, ...
    etat_rul, fiab_moteur, fiab_reducteur, mtbf_mot, mtbf_red)
%#codegen

% Déclare envoyer_donnees comme fonction externe
coder.extrinsic('envoyer_donnees');

persistent compteur
if isempty(compteur)
    compteur = 0;
end

compteur = compteur + 1;
if compteur >= 1
    compteur = 0;
    envoyer_donnees(wm, w_table, ...
        T_bobA, T_bobB, T_bobC, ...
        T_pal_DE, T_pal_NDE, T_huile, ...
        T_pal1_red, T_pal2_red, ...
        vib_moteur, vib_red, pos_galet, ...
        w_separateur,  ...
        P_hydr1, P_hydr2, ...
        pression_pompe1, pression_pompe2, ...
        contre_pression1, contre_pression2, ...
        etat_ia, proba_sain, proba_faible, proba_grave, ...
        RUL_moteur, RUL_reducteur, tendance_mot, tendance_red, ...
        etat_rul, fiab_moteur, fiab_reducteur, mtbf_mot, mtbf_red);
end
end
